/**
 * SEO Routes
 * ==========
 * Handles SEO-related endpoints:
 * - robots.txt
 * - sitemap.xml
 * - sitemap-index.xml
 */

const express = require('express');
const router = express.Router();
const { SitemapStream, streamToPromise } = require('sitemap');
const { Readable } = require('stream');

const SITE_URL = process.env.SITE_URL || 'http://localhost:3000';

/**
 * Define your site pages here
 * This should be updated based on your actual routes
 */
const getStaticPages = () => [
    { url: '/', changefreq: 'daily', priority: 1.0 },
    { url: '/about', changefreq: 'monthly', priority: 0.8 },
    { url: '/contact', changefreq: 'monthly', priority: 0.7 },
    { url: '/services', changefreq: 'weekly', priority: 0.9 },
    { url: '/blog', changefreq: 'daily', priority: 0.9 },
    { url: '/privacy-policy', changefreq: 'yearly', priority: 0.3 },
    { url: '/terms-of-service', changefreq: 'yearly', priority: 0.3 },
];

/**
 * Get dynamic pages from database (example)
 * Uncomment and modify when you have database
 */
// const getDynamicPages = async () => {
//     const posts = await Post.find({ status: 'published' }).select('slug updatedAt');
//     return posts.map(post => ({
//         url: `/blog/${post.slug}`,
//         changefreq: 'weekly',
//         priority: 0.6,
//         lastmod: post.updatedAt.toISOString(),
//     }));
// };

/**
 * robots.txt
 * ----------
 * Defines rules for search engine crawlers
 */
router.get('/robots.txt', (req, res) => {
    const robotsTxt = `# robots.txt for ${SITE_URL}
# Generated by SEO-Express

# Allow all crawlers
User-agent: *
Allow: /

# Disallow admin and private areas
Disallow: /admin/
Disallow: /api/
Disallow: /private/
Disallow: /user/dashboard/

# Disallow search results and filters
Disallow: /*?*sort=
Disallow: /*?*filter=
Disallow: /*?*page=

# Allow specific API endpoints for crawling (if needed)
# Allow: /api/public/

# Crawl-delay (optional, be careful with this)
# Crawl-delay: 1

# Sitemap location
Sitemap: ${SITE_URL}/sitemap.xml

# Search engine specific rules
# Google
User-agent: Googlebot
Allow: /

# Bing
User-agent: Bingbot
Allow: /

# Yandex
User-agent: Yandex
Allow: /

# AI Bots (GPTBot, Claude, etc.)
# Allow AI bots to crawl public content
User-agent: GPTBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: Anthropic-AI
Allow: /

User-agent: Google-Extended
Allow: /

# Block bad bots
User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: MJ12bot
Disallow: /
`;

    res.type('text/plain');
    res.send(robotsTxt);
});

/**
 * sitemap.xml
 * -----------
 * XML sitemap for search engines
 */
router.get('/sitemap.xml', async (req, res) => {
    try {
        // Get all pages
        const staticPages = getStaticPages();
        // const dynamicPages = await getDynamicPages();
        // const allPages = [...staticPages, ...dynamicPages];
        const allPages = staticPages;

        // Create sitemap stream
        const stream = new SitemapStream({ hostname: SITE_URL });

        // Create readable stream from pages
        const xmlString = await streamToPromise(
            Readable.from(allPages).pipe(stream)
        ).then((data) => data.toString());

        res.header('Content-Type', 'application/xml');
        res.header('Cache-Control', 'public, max-age=3600'); // Cache for 1 hour
        res.send(xmlString);
    } catch (error) {
        console.error('[Sitemap Error]', error);
        res.status(500).send('Error generating sitemap');
    }
});

/**
 * sitemap-index.xml
 * -----------------
 * Sitemap index for large sites with multiple sitemaps
 */
router.get('/sitemap-index.xml', (req, res) => {
    const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>${SITE_URL}/sitemap.xml</loc>
        <lastmod>${new Date().toISOString()}</lastmod>
    </sitemap>
    <sitemap>
        <loc>${SITE_URL}/sitemap-posts.xml</loc>
        <lastmod>${new Date().toISOString()}</lastmod>
    </sitemap>
    <sitemap>
        <loc>${SITE_URL}/sitemap-pages.xml</loc>
        <lastmod>${new Date().toISOString()}</lastmod>
    </sitemap>
</sitemapindex>`;

    res.header('Content-Type', 'application/xml');
    res.header('Cache-Control', 'public, max-age=3600');
    res.send(sitemapIndex);
});

/**
 * BrowserConfig.xml (for Microsoft)
 */
router.get('/browserconfig.xml', (req, res) => {
    const browserConfig = `<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <square150x150logo src="/images/mstile-150x150.png"/>
            <TileColor>#667eea</TileColor>
        </tile>
    </msapplication>
</browserconfig>`;

    res.header('Content-Type', 'application/xml');
    res.send(browserConfig);
});

/**
 * Web App Manifest (for PWA)
 */
router.get('/manifest.json', (req, res) => {
    const manifest = {
        name: process.env.SITE_NAME || 'SEO Express',
        short_name: 'SEO Express',
        description: process.env.SITE_DESCRIPTION || 'A SEO-optimized Express.js application',
        start_url: '/',
        display: 'standalone',
        background_color: '#ffffff',
        theme_color: '#667eea',
        orientation: 'portrait-primary',
        icons: [
            {
                src: '/images/icon-192x192.png',
                sizes: '192x192',
                type: 'image/png',
                purpose: 'any maskable',
            },
            {
                src: '/images/icon-512x512.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'any maskable',
            },
        ],
    };

    res.header('Content-Type', 'application/manifest+json');
    res.json(manifest);
});

/**
 * Security.txt (for security researchers)
 * https://securitytxt.org/
 */
router.get('/.well-known/security.txt', (req, res) => {
    const securityTxt = `# Security Policy
Contact: mailto:security@example.com
Expires: ${new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()}
Preferred-Languages: en, vi
Canonical: ${SITE_URL}/.well-known/security.txt
`;

    res.type('text/plain');
    res.send(securityTxt);
});

module.exports = router;
